language: node_js
node_js:
  - stable

script:
  - npm run build
  - cp ./build/index.html  ./build/404.html 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: ./build
